fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /dashboard/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /dashboard/profile

recipes:
    path: /recipes
    defaults: { _controller: AppBundle:Default:recipes }

rezeptErstellen:
    path: /rezeptErstellen
    defaults: { _controller: AppBundle:Default:rezeptErstellen }

rezepteAnzeigen:
    path: /rezepteAnzeigen
    defaults: { _controller: AppBundle:Default:rezepteAnzeigen }

rezepteLoeschen:
    path: /rezepteLoeschen/{id}
    defaults: { _controller: AppBundle:Default:rezepteLoeschen }

rezeptBearbeiten:
    path: /rezeptBearbeiten/{id}
    defaults: { _controller: AppBundle:Default:rezeptBearbeiten }
